import type { ModelPresetEntry } from "@llama-manager/core";

function escapeValue(value: string) {
  return value.replace(/\r?\n/g, " ");
}

function line(key: string, value: string | number | boolean | null) {
  if (value === null || value === "" || value === undefined) {
    return null;
  }
  return `${key} = ${escapeValue(String(value))}`;
}

const reservedEntryKeys = new Set([
  "model",
  "ctx-size",
  "c",
  "gpu-layers",
  "n-gpu-layers",
  "ngl",
  "mmproj",
  "load-on-startup",
  "stop-timeout",
]);

function extraArgLines(entry: ModelPresetEntry) {
  return Object.entries(entry.extraArgs ?? {})
    .map(
      ([rawKey, value]) =>
        [rawKey.trim().replace(/^-+/, ""), value.trim()] as const,
    )
    .filter(([key, value]) => key && value && !reservedEntryKeys.has(key))
    .map(([key, value]) => line(key, value))
    .filter((item): item is string => Boolean(item));
}

export function renderModelPresetIni(entries: ModelPresetEntry[]) {
  const lines = [
    "; Generated by llama-manager",
    "; Keys follow llama-server --models-preset format: CLI args without leading dashes.",
    "version = 1",
    "",
  ];

  for (const entry of entries) {
    lines.push(`[${entry.name}]`);
    const sectionLines = [
      line("model", entry.modelPath),
      line("ctx-size", entry.ctxSize),
      line("n-gpu-layers", entry.nGpuLayers),
      line("mmproj", entry.mmprojPath),
      line("load-on-startup", entry.loadOnStartup),
      line("stop-timeout", entry.stopTimeout),
      ...extraArgLines(entry),
    ].filter((item): item is string => Boolean(item));
    lines.push(...sectionLines, "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
