import { strict as assert } from "node:assert";
import test from "node:test";

import type { ModelPresetEntry } from "@llama-manager/core";

import { renderModelPresetIni } from "./ini.js";

function presetEntry(input: Partial<ModelPresetEntry>): ModelPresetEntry {
  return {
    id: "test-model-id",
    name: "test-model",
    modelPath: "/models/test.gguf",
    ctxSize: 4096,
    nGpuLayers: "auto",
    mmprojPath: null,
    loadOnStartup: false,
    stopTimeout: 10,
    extraArgs: {},
    ...input,
  };
}

test("renderModelPresetIni does not emit root keys before sections", () => {
  const rendered = renderModelPresetIni([
    presetEntry({
      name: "alpha",
      modelPath: "/models/alpha.gguf",
    }),
  ]);

  assert.match(rendered, /^\s*; Generated by llama-manager\n/);
  assert.doesNotMatch(rendered, /^version\s*=/m);
  assert.match(rendered, /\n\[alpha\]\nmodel = \/models\/alpha\.gguf\n/);
});
